name: 'docker build'
description: 'A Action CI plugin for building and labelling Docker images'
inputs:
  repo:
    description: 'tag to this repo/repo to push to'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
