name: 'docker build'
author: 'triptixx'
description: 'A Action CI plugin for building and labelling Docker images'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'  
  color: 'blue'
